### PR TITLE
Use progmem for two fixed strings

### LINKED ISSUE #128: Move string constants to PROGMEM
There are a couple of strings in the code that are constants (board type, version) but aren't stored in PROGMEM. These are easily movable by using the F() macro.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #128

Move two strings to PROGMEM. On a ProMicro before this change:

```
RAM:   [========  ]  77.5% (used 1984 bytes from 2560 bytes)
Flash: [========= ]  91.6% (used 26254 bytes from 28672 bytes)
```

On a ProMicro after this change:

```
RAM:   [========  ]  76.6% (used 1962 bytes from 2560 bytes)
Flash: [========= ]  91.7% (used 26290 bytes from 28672 bytes)
```

Saves 22 bytes of RAM at the expense of 36 bytes of flash.

### CODE REVIEW

File: src/mobiflight.cpp [hunk 1]
```diff
@@ -61,11 +61,10 @@ const uint8_t MEM_OFFSET_CONFIG = MEM_OFFSET_NAME + MEM_LEN_NAME + MEM_LEN_SERIA
 
 uint32_t lastAnalogAverage = 0;
 uint32_t lastAnalogRead = 0;
-uint32_t lastButtonUpdate= 0;
+uint32_t lastButtonUpdate = 0;
 uint32_t lastEncoderUpdate = 0;
 uint32_t lastServoUpdate = 0;
 
-const char type[sizeof(MOBIFLIGHT_TYPE)] = MOBIFLIGHT_TYPE;
```
Comment (neilenns) [inline src/mobiflight.cpp:68]: This is no longer needed since the string comes from PROGMEM.

File: src/mobiflight.cpp [hunk 2]
```diff
@@ -884,10 +883,10 @@ void OnGetInfo()
 {
   lastCommand = millis();
   cmdMessenger.sendCmdStart(kInfo);
-  cmdMessenger.sendCmdArg(type);
```
Comment (neilenns) [inline src/mobiflight.cpp:887]: Use the `F()` macro to get the string to come from PROGMEM.

File: src/mobiflight.cpp [hunk 3]
```diff
@@ -884,10 +883,10 @@ void OnGetInfo()
...
+  cmdMessenger.sendCmdArg(F(MOBIFLIGHT_TYPE));
   cmdMessenger.sendCmdArg(name);
   cmdMessenger.sendCmdArg(serial);
-  cmdMessenger.sendCmdArg(VERSION);
```
Comment (neilenns) [inline src/mobiflight.cpp:890]: Use the `F()` macro to get the string to come from PROGMEM.

**Comment by neilenns** [comment]
Note that there are a bunch of whitespace modifications as well due to VSCode autoformatting.

**Review by DocMoebiuz — APPROVED** [review]
Many changes due to re-formatting

Thanks for the PROGMEM improvement

**Review by DocMoebiuz — APPROVED** [review]

**Review by MobiFlight-Admin — APPROVED** [review]
thanks
