### PR TITLE
(#898)(Connector) Fix missing retrigger for ANALOG inputs at startup

### LINKED ISSUE #202: Retrigger function does not initialize current value of analog potentiometers
Firmware copy of https://github.com/MobiFlight/MobiFlight-Connector/issues/898

**Describe the bug**
The retrigger function does not initialize the current value of analog potentiometers position.

**Steps To Reproduce**

Start Mobiflight with a potentiometer config assigned to a light dimmer in the sim and pot in mid position.
Press the retrigger button
Note lights in the sim did not sync to the pot position.
Expected behavior
Retrigger should synchronize the pot position in the sim.

**Actual behavior**
Potentiometer is ignored in the retrigger. Nothing happens.

**Details**

MobiFlight Version: 9.4.0.4
FlightSim: irrelevant
AddOn: irrelevant

**Additional context**
Workaround is to move the pot, which defeats the purpose of the retrigger function.

### PR DESCRIPTION
**Pull request by GioCC**
## Description of changes
Fixes #202 
Fixes #898 (listed under Connector issues)

Included Analog input polling in the retrigger command.
An initial scan has been added to setup() to fill the value buffer for analog inputs before it is used

### CODE REVIEW

**Comment by elral** [comment]
I think initialisation of the average buffer should be part of the constructor `MFAnalog::MFAnalog` so that separate function is not required.
For my understanding all steps to get a class working should be part of the constructor if possible, if not it should be part of a `init()` function. As we have only the constructor and nothing else is required to get it working (e.g. SPI, serial, ...) I think it is the correct place to do it.

**Comment by GioCC** [comment]
@elral you're absolutely right, thanks for noticing! I changed it the way you suggest,

**Comment by elral** [comment]
@GioCC looks perfect now!

File: src/MF_Analog/MFAnalog.cpp [hunk 1]
```diff
@@ -15,20 +15,32 @@ MFAnalog::MFAnalog(uint8_t pin, const char *name, uint8_t sensitivity)
...
     _lastValue   = 0;
     pinMode(_pin, INPUT_PULLUP); // set pin to input. Could use OUTPUT for analog, but shows the intention :-)
-    analogRead(_pin);            // turn on pullup resistors
+    for (uint8_t i = 0; i < ADC_MAX_AVERAGE; i++) {
+        readBuffer();
+    }
 }
 
-void MFAnalog::update()
+void MFAnalog::readChannel(uint8_t compare)
```
Comment (DocMoebiuz) [inline src/MF_Analog/MFAnalog.cpp:23]: the parameter name `compare` could be more explicitly describing what we mean so that it becomes easier to understand when reading:

`forceReadandAlwaysTrigger`
`alwaysTrigger`

And also 
```abs(newValue - _lastValue) >= _sensitivity```

would be nicer in a short function `valueHasChanged`

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
please see my comment.

**Review by DocMoebiuz — APPROVED** [review]
Thanks @GioCC
